In [2]:
import pandas as pd
import seaborn as sns
import numpy as np 
import requests
from io import StringIO
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

In [3]:
tipsDataSet = sns.load_dataset('tips')

In [4]:
tipsDataSet.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [5]:
tipsDataSet.shape

(244, 7)

In [6]:
tipsDataSet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [7]:
tipsDataSet.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [9]:
tipsDataSet['total_bill'].value_counts()

total_bill
13.42    3
21.01    2
20.69    2
10.33    2
10.34    2
        ..
29.03    1
27.18    1
22.67    1
17.82    1
18.78    1
Name: count, Length: 229, dtype: int64

In [10]:
tipsDataSet['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [11]:
tipsDataSet['tip'].value_counts()

tip
2.00    33
3.00    23
4.00    12
2.50    10
5.00    10
        ..
1.47     1
1.17     1
4.67     1
5.92     1
1.75     1
Name: count, Length: 123, dtype: int64

In [12]:
tipsDataSet['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [13]:
tipsDataSet['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [14]:
tipsDataSet['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [15]:
tipsDataSet['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [16]:
tipsDataSet['size'].value_counts()

size
2    156
3     38
4     37
5      5
1      4
6      4
Name: count, dtype: int64

In [17]:
tipsDataSet.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [23]:
for col in tipsDataSet.loc[:,['sex','smoker','day','time','size']]:
    val = tipsDataSet[col].value_counts()
    print(val)

sex
Male      157
Female     87
Name: count, dtype: int64
smoker
No     151
Yes     93
Name: count, dtype: int64
day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64
time
Dinner    176
Lunch      68
Name: count, dtype: int64
size
2    156
3     38
4     37
5      5
1      4
6      4
Name: count, dtype: int64

In [24]:
label_en = LabelEncoder()

In [25]:
tipsDataSet.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [26]:
tipsDataSet['sex'] = label_en.fit_transform(tipsDataSet['sex'])

In [28]:
tipsDataSet.head()

   total_bill   tip  sex smoker  day    time  size
0       16.99  1.01    0     No  Sun  Dinner     2
1       10.34  1.66    1     No  Sun  Dinner     3
2       21.01  3.50    1     No  Sun  Dinner     3
3       23.68  3.31    1     No  Sun  Dinner     2
4       24.59  3.61    0     No  Sun  Dinner     4

In [29]:
tipsDataSet['smoker'] = label_en.fit_transform(tipsDataSet['smoker'])

In [30]:
tipsDataSet.head()

   total_bill   tip  sex  smoker  day    time  size
0       16.99  1.01    0       0  Sun  Dinner     2
1       10.34  1.66    1       0  Sun  Dinner     3
2       21.01  3.50    1       0  Sun  Dinner     3
3       23.68  3.31    1       0  Sun  Dinner     2
4       24.59  3.61    0       0  Sun  Dinner     4

In [32]:
tipsDataSet['smoker'].value_counts()

smoker
0    151
1     93
Name: count, dtype: int64

In [34]:
tipsDataSet['day'] = label_en.fit_transform(tipsDataSet['day'])
tipsDataSet.head()

   total_bill   tip  sex  smoker  day    time  size
0       16.99  1.01    0       0    2  Dinner     2
1       10.34  1.66    1       0    2  Dinner     3
2       21.01  3.50    1       0    2  Dinner     3
3       23.68  3.31    1       0    2  Dinner     2
4       24.59  3.61    0       0    2  Dinner     4

In [35]:
tipsDataSet['day'].value_counts()

day
1    87
2    76
3    62
0    19
Name: count, dtype: int64

In [37]:
tipsDataSet['time'] = label_en.fit_transform(tipsDataSet['time'])
tipsDataSet.head()

   total_bill   tip  sex  smoker  day  time  size
0       16.99  1.01    0       0    2     0     2
1       10.34  1.66    1       0    2     0     3
2       21.01  3.50    1       0    2     0     3
3       23.68  3.31    1       0    2     0     2
4       24.59  3.61    0       0    2     0     4

In [39]:
tipsDataSet['time'].value_counts()

time
0    176
1     68
Name: count, dtype: int64