In [43]:
import pandas as pd
import numpy as np
import seaborn as sns
import requests 
from io import StringIO
from sklearn.preprocessing import OneHotEncoder
from pandas.api.types import is_numeric_dtype

In [44]:
titan_dataset = sns.load_dataset("titanic")

In [45]:
titan_dataset.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [46]:
titan_dataset.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [47]:
titan_dataset.drop('deck', axis=1, inplace=True)

In [48]:
titan_dataset['age'] = titan_dataset['age'].fillna(titan_dataset['age'].mean())

In [49]:
titan_dataset['embark_town'] = titan_dataset['embark_town'].ffill()

In [50]:
titan_dataset['embarked'] = titan_dataset['embarked'].ffill()

In [51]:
titan_dataset.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

In [52]:
titan_dataset1 = titan_dataset.copy()
titan_dataset2 = titan_dataset.copy()

In [53]:
titan_dataset.isna().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

In [54]:
titan_dataset.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'embark_town', 'alive',
       'alone'],
      dtype='object')

In [55]:
for col in titan_dataset.loc[:, ['survived', 'pclass', 'sex', 'sibsp', 'parch', 'embarked', 'class', 'who', 'adult_male', 'embark_town', 'alive', 'alone']]:
    uni = titan_dataset[col].value_counts()
    print(uni)

survived
0    549
1    342
Name: count, dtype: int64
pclass
3    491
1    216
2    184
Name: count, dtype: int64
sex
male      577
female    314
Name: count, dtype: int64
sibsp
0    608
1    209
2     28
4     18
3     16
8      7
5      5
Name: count, dtype: int64
parch
0    678
1    118
2     80
5      5
3      5
4      4
6      1
Name: count, dtype: int64
embarked
S    644
C    169
Q     78
Name: count, dtype: int64
class
Third     491
First     216
Second    184
Name: count, dtype: int64
who
man      537
woman    271
child     83
Name: count, dtype: int64
adult_male
True     537
False    354
Name: count, dtype: int64
embark_town
Southampton    644
Cherbourg      169
Queenstown      78
Name: count, dtype: int64
alive
no     549
yes    342
Name: count, dtype: int64
alone
True     537
False    354
Name: count, dtype: int64

In [56]:
titan_dataset.shape

(891, 14)

In [57]:
titan_dataset.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

In [58]:
dummy = pd.get_dummies(titan_dataset['embarked'], prefix='embarked', prefix_sep='-', drop_first=True).astype('int64')
dummy

     embarked-Q  embarked-S
0             0           1
1             0           0
2             0           1
3             0           1
4             0           1
..          ...         ...
886           0           1
887           0           1
888           0           1
889           0           0
890           1           0

[891 rows x 2 columns]

In [59]:
dummy_val = pd.DataFrame(dummy)
dummy_val.head(2)

   embarked-Q  embarked-S
0           0           1
1           0           0

In [60]:
titan_dataset.drop('embarked', axis=1, inplace=True)

In [61]:
titan_dataset.head(2)

,survived,pclass,sex,age,sibsp,parch,fare,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,First,woman,False,Cherbourg,yes,False

In [62]:
new_titan_dataset = pd.concat([titan_dataset, dummy_val], axis=1)
new_titan_dataset.head(2)

,survived,pclass,sex,age,sibsp,parch,fare,class,who,adult_male,embark_town,alive,alone,embarked-Q,embarked-S
0,0,3,male,22.0,1,0,7.2500,Third,man,True,Southampton,no,False,0,1
1,1,1,female,38.0,1,0,71.2833,First,woman,False,Cherbourg,yes,False,0,0

In [63]:
dummy1 = pd.get_dummies(titan_dataset['embark_town'], drop_first=True).astype('int64')
dummy1.head(2)

   Queenstown  Southampton
0           0            1
1           0            0

In [64]:
dummy_val1 = pd.DataFrame(dummy1)

In [65]:
new_main_titan_dataset = pd.concat([new_titan_dataset, dummy_val1], axis=1)
new_main_titan_dataset.head(2)

,survived,pclass,sex,age,sibsp,parch,fare,class,who,adult_male,embark_town,alive,alone,embarked-Q,embarked-S,Queenstown,Southampton
0,0,3,male,22.0,1,0,7.2500,Third,man,True,Southampton,no,False,0,1,0,1
1,1,1,female,38.0,1,0,71.2833,First,woman,False,Cherbourg,yes,False,0,0,0,0

In [66]:
for col in new_main_titan_dataset.loc[:, ['adult_male', 'alone']]:
    new_main_titan_dataset[col] = new_main_titan_dataset[col].astype('int64')

In [67]:
new_main_titan_dataset.head()

,survived,pclass,sex,age,sibsp,parch,fare,class,who,adult_male,embark_town,alive,alone,embarked-Q,embarked-S,Queenstown,Southampton
0,0,3,male,22.0,1,0,7.2500,Third,man,1,Southampton,no,0,0,1,0,1
1,1,1,female,38.0,1,0,71.2833,First,woman,0,Cherbourg,yes,0,0,0,0,0
2,1,3,female,26.0,0,0,7.9250,Third,woman,0,Southampton,yes,1,0,1,0,1
3,1,1,female,35.0,1,0,53.1000,First,woman,0,Southampton,yes,0,0,1,0,1
4,0,3,male,35.0,0,0,8.0500,Third,man,1,Southampton,no,1,0,1,0,1

In [68]:

new_main_titan_dataset.drop('embark_town', axis=1, inplace=True)

In [69]:
new_main_titan_dataset.head()

,survived,pclass,sex,age,sibsp,parch,fare,class,who,adult_male,alive,alone,embarked-Q,embarked-S,Queenstown,Southampton
0,0,3,male,22.0,1,0,7.2500,Third,man,1,no,0,0,1,0,1
1,1,1,female,38.0,1,0,71.2833,First,woman,0,yes,0,0,0,0,0
2,1,3,female,26.0,0,0,7.9250,Third,woman,0,yes,1,0,1,0,1
3,1,1,female,35.0,1,0,53.1000,First,woman,0,yes,0,0,1,0,1
4,0,3,male,35.0,0,0,8.0500,Third,man,1,no,1,0,1,0,1

In [70]:
one_hot_encoding = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

In [71]:
X_categorical = titan_dataset1[['sex']]

In [72]:
encoded_data = one_hot_encoding.fit_transform(X_categorical)

In [73]:
encoded_data

array([[0., 1.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [0., 1.],
       [0., 1.]], shape=(891, 2))

In [74]:
encoded_titanic_dataset1 = pd.DataFrame(encoded_data, columns=one_hot_encoding.get_feature_names_out(['sex'])).astype('int64')

In [75]:
encoded_titanic_dataset1 = pd.concat([titan_dataset1.drop('sex', axis=1), encoded_titanic_dataset1], axis=1)

In [76]:
encoded_titanic_dataset1.head(1)

,survived,pclass,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone,sex_female,sex_male
0,0,3,22.0,1,0,7.25,S,Third,man,True,Southampton,no,False,0,1

In [77]:
Y_categorical = encoded_titanic_dataset1[['embarked']]
Y_categorical_fit = one_hot_encoding.fit_transform(Y_categorical)
encoded_titanic_dataset2 = pd.DataFrame(Y_categorical_fit, columns=one_hot_encoding.get_feature_names_out(['embarked'])).astype('int64')
encoded_titanic_dataset2 = pd.concat([encoded_titanic_dataset1.drop('embarked', axis=1), encoded_titanic_dataset2], axis=1)
encoded_titanic_dataset2.head(1)

,survived,pclass,age,sibsp,parch,fare,class,who,adult_male,embark_town,alive,alone,sex_female,sex_male,embarked_C,embarked_Q,embarked_S
0,0,3,22.0,1,0,7.25,Third,man,True,Southampton,no,False,0,1,0,0,1

In [78]:
X_categorical_fit = one_hot_encoding.fit_transform(encoded_titanic_dataset2[['class']])
encoded_titanic_dataset3 = pd.DataFrame(X_categorical_fit, columns=one_hot_encoding.get_feature_names_out(['class'])).astype('int64')
encoded_titanic_dataset3 = pd.concat([encoded_titanic_dataset2.drop('class', axis=1), encoded_titanic_dataset3], axis=1)
encoded_titanic_dataset3.head()

,survived,pclass,age,sibsp,parch,fare,who,adult_male,embark_town,alive,alone,sex_female,sex_male,embarked_C,embarked_Q,embarked_S,class_First,class_Second,class_Third
0,0,3,22.0,1,0,7.2500,man,True,Southampton,no,False,0,1,0,0,1,0,0,1
1,1,1,38.0,1,0,71.2833,woman,False,Cherbourg,yes,False,1,0,1,0,0,1,0,0
2,1,3,26.0,0,0,7.9250,woman,False,Southampton,yes,True,1,0,0,0,1,0,0,1
3,1,1,35.0,1,0,53.1000,woman,False,Southampton,yes,False,1,0,0,0,1,1,0,0
4,0,3,35.0,0,0,8.0500,man,True,Southampton,no,True,0,1,0,0,1,0,0,1

In [79]:
X_categorical_fit = one_hot_encoding.fit_transform(encoded_titanic_dataset2[['who']])
encoded_titanic_dataset3 = pd.DataFrame(X_categorical_fit, columns=one_hot_encoding.get_feature_names_out(['who'])).astype('int64')
encoded_titanic_dataset3 = pd.concat([encoded_titanic_dataset2.drop('who', axis=1), encoded_titanic_dataset3], axis=1)
encoded_titanic_dataset3.head()

,survived,pclass,age,sibsp,parch,fare,class,adult_male,embark_town,alive,alone,sex_female,sex_male,embarked_C,embarked_Q,embarked_S,who_child,who_man,who_woman
0,0,3,22.0,1,0,7.2500,Third,True,Southampton,no,False,0,1,0,0,1,0,1,0
1,1,1,38.0,1,0,71.2833,First,False,Cherbourg,yes,False,1,0,1,0,0,0,0,1
2,1,3,26.0,0,0,7.9250,Third,False,Southampton,yes,True,1,0,0,0,1,0,0,1
3,1,1,35.0,1,0,53.1000,First,False,Southampton,yes,False,1,0,0,0,1,0,0,1
4,0,3,35.0,0,0,8.0500,Third,True,Southampton,no,True,0,1,0,0,1,0,1,0

In [80]:
for col in encoded_titanic_dataset3.loc[:, ['adult_male', 'alone']]:
    encoded_titanic_dataset3[col] = encoded_titanic_dataset3[col].astype('int64')

In [81]:
encoded_titanic_dataset3.head()

,survived,pclass,age,sibsp,parch,fare,class,adult_male,embark_town,alive,alone,sex_female,sex_male,embarked_C,embarked_Q,embarked_S,who_child,who_man,who_woman
0,0,3,22.0,1,0,7.2500,Third,1,Southampton,no,0,0,1,0,0,1,0,1,0
1,1,1,38.0,1,0,71.2833,First,0,Cherbourg,yes,0,1,0,1,0,0,0,0,1
2,1,3,26.0,0,0,7.9250,Third,0,Southampton,yes,1,1,0,0,0,1,0,0,1
3,1,1,35.0,1,0,53.1000,First,0,Southampton,yes,0,1,0,0,0,1,0,0,1
4,0,3,35.0,0,0,8.0500,Third,1,Southampton,no,1,0,1,0,0,1,0,1,0

In [82]:
fit_x_cat = one_hot_encoding.fit_transform(encoded_titanic_dataset3[['class']])
encoded_titanic_dataset4 = pd.DataFrame(fit_x_cat, columns=one_hot_encoding.get_feature_names_out(['class'])).astype('int64')
encoded_titanic_dataset4 = pd.concat([encoded_titanic_dataset3.drop('class', axis=1), encoded_titanic_dataset4], axis=1)
encoded_titanic_dataset4.head()

,survived,pclass,age,sibsp,parch,fare,adult_male,embark_town,alive,alone,...,sex_male,embarked_C,embarked_Q,embarked_S,who_child,who_man,who_woman,class_First,class_Second,class_Third
0,0,3,22.0,1,0,7.2500,1,Southampton,no,0,...,1,0,0,1,0,1,0,0,0,1
1,1,1,38.0,1,0,71.2833,0,Cherbourg,yes,0,...,0,1,0,0,0,0,1,1,0,0
2,1,3,26.0,0,0,7.9250,0,Southampton,yes,1,...,0,0,0,1,0,0,1,0,0,1
3,1,1,35.0,1,0,53.1000,0,Southampton,yes,0,...,0,0,0,1,0,0,1,1,0,0
4,0,3,35.0,0,0,8.0500,1,Southampton,no,1,...,1,0,0,1,0,1,0,0,0,1

In [83]:
fit_x_cat = one_hot_encoding.fit_transform(encoded_titanic_dataset3[['embark_town']])
encoded_titanic_dataset5 = pd.DataFrame(fit_x_cat, columns=one_hot_encoding.get_feature_names_out(['embark_town'])).astype('int64')
encoded_titanic_dataset5 = pd.concat([encoded_titanic_dataset4.drop('embark_town', axis=1), encoded_titanic_dataset5], axis=1)
encoded_titanic_dataset5.head()

,survived,pclass,age,sibsp,parch,fare,adult_male,alive,alone,sex_female,...,embarked_S,who_child,who_man,who_woman,class_First,class_Second,class_Third,embark_town_Cherbourg,embark_town_Queenstown,embark_town_Southampton
0,0,3,22.0,1,0,7.2500,1,no,0,0,...,1,0,1,0,0,0,1,0,0,1
1,1,1,38.0,1,0,71.2833,0,yes,0,1,...,0,0,0,1,1,0,0,1,0,0
2,1,3,26.0,0,0,7.9250,0,yes,1,1,...,1,0,0,1,0,0,1,0,0,1
3,1,1,35.0,1,0,53.1000,0,yes,0,1,...,1,0,0,1,1,0,0,0,0,1
4,0,3,35.0,0,0,8.0500,1,no,1,0,...,1,0,1,0,0,0,1,0,0,1

In [84]:
fit_x_cat = one_hot_encoding.fit_transform(encoded_titanic_dataset3[['alive']])
encoded_titanic_dataset6 = pd.DataFrame(fit_x_cat, columns=one_hot_encoding.get_feature_names_out(['alive'])).astype('int64')
encoded_titanic_dataset6 = pd.concat([encoded_titanic_dataset5.drop('alive', axis=1), encoded_titanic_dataset6], axis=1)
encoded_titanic_dataset6.head()

,survived,pclass,age,sibsp,parch,fare,adult_male,alone,sex_female,sex_male,...,who_man,who_woman,class_First,class_Second,class_Third,embark_town_Cherbourg,embark_town_Queenstown,embark_town_Southampton,alive_no,alive_yes
0,0,3,22.0,1,0,7.2500,1,0,0,1,...,1,0,0,0,1,0,0,1,1,0
1,1,1,38.0,1,0,71.2833,0,0,1,0,...,0,1,1,0,0,1,0,0,0,1
2,1,3,26.0,0,0,7.9250,0,1,1,0,...,0,1,0,0,1,0,0,1,0,1
3,1,1,35.0,1,0,53.1000,0,0,1,0,...,0,1,1,0,0,0,0,1,0,1
4,0,3,35.0,0,0,8.0500,1,1,0,1,...,1,0,0,0,1,0,0,1,1,0