In [82]:
import pandas as pd
import numpy as np
import seaborn as sns
import requests
from io import StringIO
from sklearn.preprocessing import OrdinalEncoder
from pandas.api.types import is_numeric_dtype

In [83]:
tip_data_set = sns.load_dataset('tips')

In [84]:
tip_data_set.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [85]:
tip_data_set.isna().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [86]:
ordinal_en = OrdinalEncoder()

In [87]:
tip_data_set['sex'] = ordinal_en.fit_transform(tip_data_set[['sex']]).astype('int64')

In [88]:
tip_data_set['sex'].value_counts()

sex
1    157
0     87
Name: count, dtype: int64

In [89]:
tip_data_set.head()

   total_bill   tip  sex smoker  day    time  size
0       16.99  1.01    0     No  Sun  Dinner     2
1       10.34  1.66    1     No  Sun  Dinner     3
2       21.01  3.50    1     No  Sun  Dinner     3
3       23.68  3.31    1     No  Sun  Dinner     2
4       24.59  3.61    0     No  Sun  Dinner     4

In [90]:
smok_fit = ordinal_en.fit(tip_data_set[['smoker']])

In [91]:
smok_fit

OrdinalEncoder()

In [92]:
tip_data_set['smoker'] = smok_fit.transform(tip_data_set[['smoker']]).astype('int64')

In [93]:
tip_data_set.head()

   total_bill   tip  sex  smoker  day    time  size
0       16.99  1.01    0       0  Sun  Dinner     2
1       10.34  1.66    1       0  Sun  Dinner     3
2       21.01  3.50    1       0  Sun  Dinner     3
3       23.68  3.31    1       0  Sun  Dinner     2
4       24.59  3.61    0       0  Sun  Dinner     4

In [94]:
tip_data_set['smoker'].value_counts()

smoker
0    151
1     93
Name: count, dtype: int64

In [95]:
tip_data_set['day'] = ordinal_en.fit_transform(tip_data_set[['day']]).astype('int64')

In [96]:
tip_data_set['day'].value_counts()

day
1    87
2    76
3    62
0    19
Name: count, dtype: int64

In [97]:
tip_data_set.head()

   total_bill   tip  sex  smoker  day    time  size
0       16.99  1.01    0       0    2  Dinner     2
1       10.34  1.66    1       0    2  Dinner     3
2       21.01  3.50    1       0    2  Dinner     3
3       23.68  3.31    1       0    2  Dinner     2
4       24.59  3.61    0       0    2  Dinner     4

In [98]:
tip_data_set['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [99]:
tip_data_set['time'] = ordinal_en.fit_transform(tip_data_set[['time']]).astype('int64')

In [100]:
tip_data_set.tail()

     total_bill   tip  sex  smoker  day  time  size
239       29.03  5.92    1       0    1     0     3
240       27.18  2.00    0       1    1     0     2
241       22.67  2.00    1       1    1     0     2
242       17.82  1.75    1       0    1     0     2
243       18.78  3.00    0       0    3     0     2

In [101]:
peng_data_set = sns.load_dataset('penguins')

In [102]:
peng_data_set.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

In [103]:
peng_data_set.isna().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [104]:
peng_data_set['sex'] = peng_data_set['sex'].ffill()

In [105]:
peng_data_set['bill_length_mm'] = peng_data_set['bill_length_mm'].fillna(peng_data_set['bill_length_mm'].mean())

In [106]:
peng_data_set['bill_depth_mm'] = peng_data_set['bill_depth_mm'].fillna(peng_data_set['bill_depth_mm'].mean())

In [107]:
peng_data_set['flipper_length_mm'] = peng_data_set['flipper_length_mm'].fillna(peng_data_set['flipper_length_mm'].mean())

In [108]:
peng_data_set['body_mass_g'] = peng_data_set['body_mass_g'].fillna(peng_data_set['body_mass_g'].mean())

In [109]:
peng_data_set.isna().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

In [110]:
for col in peng_data_set.loc[:, ['species','island','sex']]:
    peng_data_set[col] = ordinal_en.fit_transform(peng_data_set[[col]]).astype('int64')

In [111]:
peng_data_set.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,0,2,39.10000,18.70000,181.000000,3750.000000,1
1,0,2,39.50000,17.40000,186.000000,3800.000000,0
2,0,2,40.30000,18.00000,195.000000,3250.000000,0
3,0,2,43.92193,17.15117,200.915205,4201.754386,0
4,0,2,36.70000,19.30000,193.000000,3450.000000,0