In [2]:
import pandas as pd
import seaborn as sns
import numpy as np 
import requests
from io import StringIO
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

In [3]:
tipsDataSet = sns.load_dataset('tips')

In [4]:
tipsDataSet.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [5]:
tipsDataSet.shape

(244, 7)

In [6]:
tipsDataSet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [7]:
tipsDataSet.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [9]:
tipsDataSet['total_bill'].value_counts()

total_bill
13.42    3
21.01    2
20.69    2
10.33    2
10.34    2
        ..
29.03    1
27.18    1
22.67    1
17.82    1
18.78    1
Name: count, Length: 229, dtype: int64

In [10]:
tipsDataSet['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [11]:
tipsDataSet['tip'].value_counts()

tip
2.00    33
3.00    23
4.00    12
2.50    10
5.00    10
        ..
1.47     1
1.17     1
4.67     1
5.92     1
1.75     1
Name: count, Length: 123, dtype: int64

In [12]:
tipsDataSet['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [13]:
tipsDataSet['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [14]:
tipsDataSet['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [15]:
tipsDataSet['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [16]:
tipsDataSet['size'].value_counts()

size
2    156
3     38
4     37
5      5
1      4
6      4
Name: count, dtype: int64

In [17]:
tipsDataSet.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [23]:
for col in tipsDataSet.loc[:,['sex','smoker','day','time','size']]:
    val = tipsDataSet[col].value_counts()
    print(val)

sex
Male      157
Female     87
Name: count, dtype: int64
smoker
No     151
Yes     93
Name: count, dtype: int64
day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64
time
Dinner    176
Lunch      68
Name: count, dtype: int64
size
2    156
3     38
4     37
5      5
1      4
6      4
Name: count, dtype: int64

In [24]:
label_en = LabelEncoder()

In [25]:
tipsDataSet.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [26]:
tipsDataSet['sex'] = label_en.fit_transform(tipsDataSet['sex'])

In [28]:
tipsDataSet.head()

   total_bill   tip  sex smoker  day    time  size
0       16.99  1.01    0     No  Sun  Dinner     2
1       10.34  1.66    1     No  Sun  Dinner     3
2       21.01  3.50    1     No  Sun  Dinner     3
3       23.68  3.31    1     No  Sun  Dinner     2
4       24.59  3.61    0     No  Sun  Dinner     4

In [29]:
tipsDataSet['smoker'] = label_en.fit_transform(tipsDataSet['smoker'])

In [30]:
tipsDataSet.head()

   total_bill   tip  sex  smoker  day    time  size
0       16.99  1.01    0       0  Sun  Dinner     2
1       10.34  1.66    1       0  Sun  Dinner     3
2       21.01  3.50    1       0  Sun  Dinner     3
3       23.68  3.31    1       0  Sun  Dinner     2
4       24.59  3.61    0       0  Sun  Dinner     4

In [32]:
tipsDataSet['smoker'].value_counts()

smoker
0    151
1     93
Name: count, dtype: int64

In [34]:
tipsDataSet['day'] = label_en.fit_transform(tipsDataSet['day'])
tipsDataSet.head()

   total_bill   tip  sex  smoker  day    time  size
0       16.99  1.01    0       0    2  Dinner     2
1       10.34  1.66    1       0    2  Dinner     3
2       21.01  3.50    1       0    2  Dinner     3
3       23.68  3.31    1       0    2  Dinner     2
4       24.59  3.61    0       0    2  Dinner     4

In [35]:
tipsDataSet['day'].value_counts()

day
1    87
2    76
3    62
0    19
Name: count, dtype: int64

In [37]:
tipsDataSet['time'] = label_en.fit_transform(tipsDataSet['time'])
tipsDataSet.head()

   total_bill   tip  sex  smoker  day  time  size
0       16.99  1.01    0       0    2     0     2
1       10.34  1.66    1       0    2     0     3
2       21.01  3.50    1       0    2     0     3
3       23.68  3.31    1       0    2     0     2
4       24.59  3.61    0       0    2     0     4

In [39]:
tipsDataSet['time'].value_counts()

time
0    176
1     68
Name: count, dtype: int64

In [46]:
url1 = "https://raw.githubusercontent.com/pooja2512/Adult-Census-Income/refs/heads/master/adult.csv"
data1 = requests.get(url1)
str_io1 = StringIO(data1.text)
adult_in_d = pd.read_csv(str_io1)

In [47]:
adult_in_d.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,?,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K

In [48]:
adult_in_d.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education.num',
       'marital.status', 'occupation', 'relationship', 'race', 'sex',
       'capital.gain', 'capital.loss', 'hours.per.week', 'native.country',
       'income'],
      dtype='object')

In [49]:
adult_in_d['workclass'].value_counts()

workclass
Private             22696
Self-emp-not-inc     2541
Local-gov            2093
?                    1836
State-gov            1298
Self-emp-inc         1116
Federal-gov           960
Without-pay            14
Never-worked            7
Name: count, dtype: int64

In [50]:
adult_in_d.isna().sum()

age               0
workclass         0
fnlwgt            0
education         0
education.num     0
marital.status    0
occupation        0
relationship      0
race              0
sex               0
capital.gain      0
capital.loss      0
hours.per.week    0
native.country    0
income            0
dtype: int64

In [51]:
adult_in_d['education'].value_counts()

education
HS-grad         10501
Some-college     7291
Bachelors        5355
Masters          1723
Assoc-voc        1382
11th             1175
Assoc-acdm       1067
10th              933
7th-8th           646
Prof-school       576
9th               514
12th              433
Doctorate         413
5th-6th           333
1st-4th           168
Preschool          51
Name: count, dtype: int64

In [52]:
adult_in_d['marital.status'].value_counts()

marital.status
Married-civ-spouse       14976
Never-married            10683
Divorced                  4443
Separated                 1025
Widowed                    993
Married-spouse-absent      418
Married-AF-spouse           23
Name: count, dtype: int64

In [53]:
adult_in_d.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education.num',
       'marital.status', 'occupation', 'relationship', 'race', 'sex',
       'capital.gain', 'capital.loss', 'hours.per.week', 'native.country',
       'income'],
      dtype='object')

In [54]:
adult_in_d['occupation'].value_counts()

occupation
Prof-specialty       4140
Craft-repair         4099
Exec-managerial      4066
Adm-clerical         3770
Sales                3650
Other-service        3295
Machine-op-inspct    2002
?                    1843
Transport-moving     1597
Handlers-cleaners    1370
Farming-fishing       994
Tech-support          928
Protective-serv       649
Priv-house-serv       149
Armed-Forces            9
Name: count, dtype: int64

In [55]:
adult_in_d['relationship'].value_counts()

relationship
Husband           13193
Not-in-family      8305
Own-child          5068
Unmarried          3446
Wife               1568
Other-relative      981
Name: count, dtype: int64

In [56]:
adult_in_d.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education.num',
       'marital.status', 'occupation', 'relationship', 'race', 'sex',
       'capital.gain', 'capital.loss', 'hours.per.week', 'native.country',
       'income'],
      dtype='object')

In [58]:
adult_in_d['race'].value_counts()

race
White                 27816
Black                  3124
Asian-Pac-Islander     1039
Amer-Indian-Eskimo      311
Other                   271
Name: count, dtype: int64

In [59]:
adult_in_d['sex'].value_counts()

sex
Male      21790
Female    10771
Name: count, dtype: int64

In [64]:
adult_in_d['income'].value_counts()

income
<=50K    24720
>50K      7841
Name: count, dtype: int64