In [293]:
import pandas as pd
import seaborn as sns
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

In [294]:
titanicdataset = sns.load_dataset('titanic')
titanicdataset.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [295]:
titanicdataset.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [296]:
titanicdataset1 = titanicdataset.copy()
titanicdataset2 = titanicdataset.copy()
titanicdataset3 = titanicdataset.copy()
titanicdataset4 = titanicdataset.copy()
titanicdataset5 = titanicdataset.copy()
titanicdataset6 = titanicdataset.copy()
titanicdataset7 = titanicdataset.copy()
titanicdataset8 = titanicdataset.copy()

In [297]:
titanicdataset['who'].value_counts()

who
man      537
woman    271
child     83
Name: count, dtype: int64

In [298]:
titanicdataset.drop('deck', axis=1, inplace=True)

In [299]:
titanicdataset.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

In [300]:
titanicdataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  embark_town  889 non-null    object
 12  alive        891 non-null    object
 13  alone        891 non-null    bool
dtypes: bool(2), category(1), float64(2), int64(4), object(5)
memory usage: 79.4+ KB

In [301]:
titanicdataset.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
embark_town      2
alive            0
alone            0
dtype: int64

In [302]:
titanicdataset['embarked'] = titanicdataset['embarked'].ffill()

In [303]:
titanicdataset['embark_town'] = titanicdataset['embark_town'].ffill()

In [304]:
titanicdataset.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         0
class            0
who              0
adult_male       0
embark_town      0
alive            0
alone            0
dtype: int64

In [305]:
titanicdataset['age'] = titanicdataset['age'].fillna(titanicdataset['age'].mean())

In [306]:
titanicdataset.isna().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

In [307]:
label_en = LabelEncoder()

In [308]:
titanicdataset['sex'] = label_en.fit_transform(titanicdataset['sex'])

In [309]:
titanicdataset.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,1,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,0,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,0,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,0,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,1,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

In [310]:
titanicdataset['embarked'] = label_en.fit_transform(titanicdataset['embarked'])

In [311]:
titanicdataset.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,1,22.0,1,0,7.2500,2,Third,man,True,Southampton,no,False
1,1,1,0,38.0,1,0,71.2833,0,First,woman,False,Cherbourg,yes,False
2,1,3,0,26.0,0,0,7.9250,2,Third,woman,False,Southampton,yes,True
3,1,1,0,35.0,1,0,53.1000,2,First,woman,False,Southampton,yes,False
4,0,3,1,35.0,0,0,8.0500,2,Third,man,True,Southampton,no,True

In [312]:
titanicdataset['embarked'].value_counts()

embarked
2    644
0    169
1     78
Name: count, dtype: int64

In [313]:
encoded_who = label_en.fit(titanicdataset['who'])
titanicdataset.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,1,22.0,1,0,7.2500,2,Third,man,True,Southampton,no,False
1,1,1,0,38.0,1,0,71.2833,0,First,woman,False,Cherbourg,yes,False
2,1,3,0,26.0,0,0,7.9250,2,Third,woman,False,Southampton,yes,True
3,1,1,0,35.0,1,0,53.1000,2,First,woman,False,Southampton,yes,False
4,0,3,1,35.0,0,0,8.0500,2,Third,man,True,Southampton,no,True

In [314]:
encoded_who

LabelEncoder()

In [315]:
titanicdataset['who'] = encoded_who.transform(titanicdataset['who'])

In [316]:
titanicdataset.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,1,22.0,1,0,7.2500,2,Third,1,True,Southampton,no,False
1,1,1,0,38.0,1,0,71.2833,0,First,2,False,Cherbourg,yes,False
2,1,3,0,26.0,0,0,7.9250,2,Third,2,False,Southampton,yes,True
3,1,1,0,35.0,1,0,53.1000,2,First,2,False,Southampton,yes,False
4,0,3,1,35.0,0,0,8.0500,2,Third,1,True,Southampton,no,True

In [317]:
titanicdataset['who'].value_counts()

who
1    537
2    271
0     83
Name: count, dtype: int64

In [318]:
titanicdataset2['sex'] = titanicdataset2['sex'].replace(['male','female'],[1,0])

C:\Users\MD Maruf\AppData\Local\Temp\ipykernel_19008\2842368984.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  titanicdataset2['sex'] = titanicdataset2['sex'].replace(['male','female'],[1,0])

In [319]:
titanicdataset2.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,1,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,0,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,0,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,0,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,1,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [320]:
titanicdataset2['adult_male'] = titanicdataset2['adult_male'].astype('int64')

In [321]:
titanicdataset2.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,1,22.0,1,0,7.2500,S,Third,man,1,NaN,Southampton,no,False
1,1,1,0,38.0,1,0,71.2833,C,First,woman,0,C,Cherbourg,yes,False
2,1,3,0,26.0,0,0,7.9250,S,Third,woman,0,NaN,Southampton,yes,True
3,1,1,0,35.0,1,0,53.1000,S,First,woman,0,C,Southampton,yes,False
4,0,3,1,35.0,0,0,8.0500,S,Third,man,1,NaN,Southampton,no,True

In [322]:
titanicdataset2['alone'] = titanicdataset2['alone'].astype('int64')

In [323]:
titanicdataset2.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,1,22.0,1,0,7.2500,S,Third,man,1,NaN,Southampton,no,0
1,1,1,0,38.0,1,0,71.2833,C,First,woman,0,C,Cherbourg,yes,0
2,1,3,0,26.0,0,0,7.9250,S,Third,woman,0,NaN,Southampton,yes,1
3,1,1,0,35.0,1,0,53.1000,S,First,woman,0,C,Southampton,yes,0
4,0,3,1,35.0,0,0,8.0500,S,Third,man,1,NaN,Southampton,no,1

In [324]:
for col in titanicdataset3.loc[:,['adult_male','alone']]:
    titanicdataset3[col] = titanicdataset3[col].astype('int64')

In [325]:
titanicdataset3.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,1,NaN,Southampton,no,0
1,1,1,female,38.0,1,0,71.2833,C,First,woman,0,C,Cherbourg,yes,0
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,0,NaN,Southampton,yes,1
3,1,1,female,35.0,1,0,53.1000,S,First,woman,0,C,Southampton,yes,0
4,0,3,male,35.0,0,0,8.0500,S,Third,man,1,NaN,Southampton,no,1

In [326]:
#one hot encoding
dummy = pd.get_dummies(titanicdataset1['embarked'],drop_first=True, prefix='embarked', prefix_sep='_').astype('int64')
dummy

     embarked_Q  embarked_S
0             0           1
1             0           0
2             0           1
3             0           1
4             0           1
..          ...         ...
886           0           1
887           0           1
888           0           1
889           0           0
890           1           0

[891 rows x 2 columns]

In [327]:
dummy_val = pd.DataFrame(dummy)

In [328]:
titanicdataset3.drop(titanicdataset['embarked'], inplace=True)

In [329]:
new_embark = pd.concat([titanicdataset, dummy_val], axis=1)
new_embark.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone,embarked_Q,embarked_S
0,0,3,1,22.0,1,0,7.2500,2,Third,1,True,Southampton,no,False,0,1
1,1,1,0,38.0,1,0,71.2833,0,First,2,False,Cherbourg,yes,False,0,0
2,1,3,0,26.0,0,0,7.9250,2,Third,2,False,Southampton,yes,True,0,1
3,1,1,0,35.0,1,0,53.1000,2,First,2,False,Southampton,yes,False,0,1
4,0,3,1,35.0,0,0,8.0500,2,Third,1,True,Southampton,no,True,0,1

In [330]:
dummy1 = pd.get_dummies(titanicdataset3['embark_town'],drop_first=True).astype('int64')
dummy1

     Queenstown  Southampton
3             0            1
4             0            1
5             1            0
6             0            1
7             0            1
..          ...          ...
886           0            1
887           0            1
888           0            1
889           0            0
890           1            0

[888 rows x 2 columns]

In [332]:
dummy1_val = pd.DataFrame(dummy1)
new_embarked = pd.concat([titanicdataset3, dummy1_val], axis=1)
new_embarked.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,Queenstown,Southampton
3,1,1,female,35.0,1,0,53.1000,S,First,woman,0,C,Southampton,yes,0,0,1
4,0,3,male,35.0,0,0,8.0500,S,Third,man,1,NaN,Southampton,no,1,0,1
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,1,NaN,Queenstown,no,1,1,0
6,0,1,male,54.0,0,0,51.8625,S,First,man,1,E,Southampton,no,1,0,1
7,0,3,male,2.0,3,1,21.0750,S,Third,child,0,NaN,Southampton,no,0,0,1