In [243]:
import pandas as pd
import seaborn as sns
import numpy as np 
import requests
from io import StringIO
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
from pandas.api.types import is_numeric_dtype

In [244]:
tipsDataSet = sns.load_dataset('tips')

In [245]:
tipsDataSet.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [246]:
tipsDataSet.shape

(244, 7)

In [247]:
tipsDataSet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [248]:
tipsDataSet.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [249]:
tipsDataSet['total_bill'].value_counts()

total_bill
13.42    3
21.01    2
20.69    2
10.33    2
10.34    2
        ..
29.03    1
27.18    1
22.67    1
17.82    1
18.78    1
Name: count, Length: 229, dtype: int64

In [250]:
tipsDataSet['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [251]:
tipsDataSet['tip'].value_counts()

tip
2.00    33
3.00    23
4.00    12
2.50    10
5.00    10
        ..
1.47     1
1.17     1
4.67     1
5.92     1
1.75     1
Name: count, Length: 123, dtype: int64

In [252]:
tipsDataSet['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [253]:
tipsDataSet['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [254]:
tipsDataSet['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [255]:
tipsDataSet['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [256]:
tipsDataSet['size'].value_counts()

size
2    156
3     38
4     37
5      5
1      4
6      4
Name: count, dtype: int64

In [257]:
tipsDataSet.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [258]:
for col in tipsDataSet.loc[:,['sex','smoker','day','time','size']]:
    val = tipsDataSet[col].value_counts()
    print(val)

sex
Male      157
Female     87
Name: count, dtype: int64
smoker
No     151
Yes     93
Name: count, dtype: int64
day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64
time
Dinner    176
Lunch      68
Name: count, dtype: int64
size
2    156
3     38
4     37
5      5
1      4
6      4
Name: count, dtype: int64

Label encoding Start

In [259]:
label_en = LabelEncoder()

In [260]:
tipsDataSet.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [261]:
tipsDataSet['sex'] = label_en.fit_transform(tipsDataSet['sex'])

In [262]:
tipsDataSet.head()

   total_bill   tip  sex smoker  day    time  size
0       16.99  1.01    0     No  Sun  Dinner     2
1       10.34  1.66    1     No  Sun  Dinner     3
2       21.01  3.50    1     No  Sun  Dinner     3
3       23.68  3.31    1     No  Sun  Dinner     2
4       24.59  3.61    0     No  Sun  Dinner     4

In [263]:
tipsDataSet['smoker'] = label_en.fit_transform(tipsDataSet['smoker'])

In [264]:
tipsDataSet.head()

   total_bill   tip  sex  smoker  day    time  size
0       16.99  1.01    0       0  Sun  Dinner     2
1       10.34  1.66    1       0  Sun  Dinner     3
2       21.01  3.50    1       0  Sun  Dinner     3
3       23.68  3.31    1       0  Sun  Dinner     2
4       24.59  3.61    0       0  Sun  Dinner     4

In [265]:
tipsDataSet['smoker'].value_counts()

smoker
0    151
1     93
Name: count, dtype: int64

In [266]:
tipsDataSet['day'] = label_en.fit_transform(tipsDataSet['day'])
tipsDataSet.head()

   total_bill   tip  sex  smoker  day    time  size
0       16.99  1.01    0       0    2  Dinner     2
1       10.34  1.66    1       0    2  Dinner     3
2       21.01  3.50    1       0    2  Dinner     3
3       23.68  3.31    1       0    2  Dinner     2
4       24.59  3.61    0       0    2  Dinner     4

In [267]:
tipsDataSet['day'].value_counts()

day
1    87
2    76
3    62
0    19
Name: count, dtype: int64

In [268]:
tipsDataSet['time'] = label_en.fit_transform(tipsDataSet['time'])
tipsDataSet.head()

   total_bill   tip  sex  smoker  day  time  size
0       16.99  1.01    0       0    2     0     2
1       10.34  1.66    1       0    2     0     3
2       21.01  3.50    1       0    2     0     3
3       23.68  3.31    1       0    2     0     2
4       24.59  3.61    0       0    2     0     4

In [269]:
tipsDataSet['time'].value_counts()

time
0    176
1     68
Name: count, dtype: int64

In [270]:
url1 = "https://raw.githubusercontent.com/pooja2512/Adult-Census-Income/refs/heads/master/adult.csv"
data1 = requests.get(url1)
str_io1 = StringIO(data1.text)
adult_in_d = pd.read_csv(str_io1)

In [271]:
adult_in_d.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,?,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K

In [272]:
adult_in_d.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education.num',
       'marital.status', 'occupation', 'relationship', 'race', 'sex',
       'capital.gain', 'capital.loss', 'hours.per.week', 'native.country',
       'income'],
      dtype='object')

In [273]:
adult_in_d['workclass'].value_counts()

workclass
Private             22696
Self-emp-not-inc     2541
Local-gov            2093
?                    1836
State-gov            1298
Self-emp-inc         1116
Federal-gov           960
Without-pay            14
Never-worked            7
Name: count, dtype: int64

In [274]:
adult_in_d.isna().sum()

age               0
workclass         0
fnlwgt            0
education         0
education.num     0
marital.status    0
occupation        0
relationship      0
race              0
sex               0
capital.gain      0
capital.loss      0
hours.per.week    0
native.country    0
income            0
dtype: int64

In [275]:
adult_in_d['education'].value_counts()

education
HS-grad         10501
Some-college     7291
Bachelors        5355
Masters          1723
Assoc-voc        1382
11th             1175
Assoc-acdm       1067
10th              933
7th-8th           646
Prof-school       576
9th               514
12th              433
Doctorate         413
5th-6th           333
1st-4th           168
Preschool          51
Name: count, dtype: int64

In [276]:
adult_in_d['marital.status'].value_counts()

marital.status
Married-civ-spouse       14976
Never-married            10683
Divorced                  4443
Separated                 1025
Widowed                    993
Married-spouse-absent      418
Married-AF-spouse           23
Name: count, dtype: int64

In [277]:
adult_in_d.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education.num',
       'marital.status', 'occupation', 'relationship', 'race', 'sex',
       'capital.gain', 'capital.loss', 'hours.per.week', 'native.country',
       'income'],
      dtype='object')

In [278]:
adult_in_d['native.country'].value_counts()

native.country
United-States                 29170
Mexico                          643
?                               583
Philippines                     198
Germany                         137
Canada                          121
Puerto-Rico                     114
El-Salvador                     106
India                           100
Cuba                             95
England                          90
Jamaica                          81
South                            80
China                            75
Italy                            73
Dominican-Republic               70
Vietnam                          67
Guatemala                        64
Japan                            62
Poland                           60
Columbia                         59
Taiwan                           51
Haiti                            44
Iran                             43
Portugal                         37
Nicaragua                        34
Peru                             31
Greece                           29
France                           29
Ecuador                          28
Ireland                          24
Hong                             20
Trinadad&Tobago                  19
Cambodia                         19
Thailand                         18
Laos                             18
Yugoslavia                       16
Outlying-US(Guam-USVI-etc)       14
Hungary                          13
Honduras                         13
Scotland                         12
Holand-Netherlands                1
Name: count, dtype: int64

In [279]:
adult_in_d['occupation'].value_counts()

occupation
Prof-specialty       4140
Craft-repair         4099
Exec-managerial      4066
Adm-clerical         3770
Sales                3650
Other-service        3295
Machine-op-inspct    2002
?                    1843
Transport-moving     1597
Handlers-cleaners    1370
Farming-fishing       994
Tech-support          928
Protective-serv       649
Priv-house-serv       149
Armed-Forces            9
Name: count, dtype: int64

In [280]:
adult_in_d['relationship'].value_counts()

relationship
Husband           13193
Not-in-family      8305
Own-child          5068
Unmarried          3446
Wife               1568
Other-relative      981
Name: count, dtype: int64

In [281]:
adult_in_d.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education.num',
       'marital.status', 'occupation', 'relationship', 'race', 'sex',
       'capital.gain', 'capital.loss', 'hours.per.week', 'native.country',
       'income'],
      dtype='object')

In [282]:
adult_in_d['native.country'].value_counts()

native.country
United-States                 29170
Mexico                          643
?                               583
Philippines                     198
Germany                         137
Canada                          121
Puerto-Rico                     114
El-Salvador                     106
India                           100
Cuba                             95
England                          90
Jamaica                          81
South                            80
China                            75
Italy                            73
Dominican-Republic               70
Vietnam                          67
Guatemala                        64
Japan                            62
Poland                           60
Columbia                         59
Taiwan                           51
Haiti                            44
Iran                             43
Portugal                         37
Nicaragua                        34
Peru                             31
Greece                           29
France                           29
Ecuador                          28
Ireland                          24
Hong                             20
Trinadad&Tobago                  19
Cambodia                         19
Thailand                         18
Laos                             18
Yugoslavia                       16
Outlying-US(Guam-USVI-etc)       14
Hungary                          13
Honduras                         13
Scotland                         12
Holand-Netherlands                1
Name: count, dtype: int64

In [283]:
adult_in_d['race'].value_counts()

race
White                 27816
Black                  3124
Asian-Pac-Islander     1039
Amer-Indian-Eskimo      311
Other                   271
Name: count, dtype: int64

In [284]:
adult_in_d['sex'].value_counts()

sex
Male      21790
Female    10771
Name: count, dtype: int64

In [285]:
adult_in_d['income'].value_counts()

income
<=50K    24720
>50K      7841
Name: count, dtype: int64

In [286]:
adult_in_d.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education.num',
       'marital.status', 'occupation', 'relationship', 'race', 'sex',
       'capital.gain', 'capital.loss', 'hours.per.week', 'native.country',
       'income'],
      dtype='object')

In [287]:
adult_in_d['workclass'] = label_en.fit_transform(adult_in_d['workclass'])
adult_in_d.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,0,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,4,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,0,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,4,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,4,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K

In [288]:
adult_in_d['workclass'].value_counts()

workclass
4    22696
6     2541
2     2093
0     1836
7     1298
5     1116
1      960
8       14
3        7
Name: count, dtype: int64

In [289]:
edu_en = label_en.fit(adult_in_d['education'])
edu_en

LabelEncoder()

In [290]:
adult_in_d['education'] = edu_en.transform(adult_in_d['education'])

In [291]:
adult_in_d.head(2)

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,0,77053,11,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,4,132870,11,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K

In [292]:
adult_in_d['education'].value_counts()

education
11    10501
15     7291
9      5355
12     1723
8      1382
1      1175
7      1067
0       933
5       646
14      576
6       514
2       433
10      413
4       333
3       168
13       51
Name: count, dtype: int64

In [293]:
merit_en = label_en.fit(adult_in_d['marital.status'])
merit_en

LabelEncoder()

In [294]:
adult_in_d['marital.status'] = label_en.transform(adult_in_d['marital.status'])

In [295]:
adult_in_d['marital.status'].value_counts()

marital.status
2    14976
4    10683
0     4443
5     1025
6      993
3      418
1       23
Name: count, dtype: int64

In [296]:
adult_in_d.head(2)

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,0,77053,11,9,6,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,4,132870,11,9,6,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K

In [297]:
occu_en = label_en.fit(adult_in_d['occupation'])
occu_en

LabelEncoder()

In [298]:
adult_in_d['occupation'] = occu_en.transform(adult_in_d['occupation'])

In [299]:
adult_in_d['occupation'].value_counts()

occupation
10    4140
3     4099
4     4066
1     3770
12    3650
8     3295
7     2002
0     1843
14    1597
6     1370
5      994
13     928
11     649
9      149
2        9
Name: count, dtype: int64

In [300]:
adult_in_d.head(3)

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,0,77053,11,9,6,0,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,4,132870,11,9,6,4,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,0,186061,15,10,6,0,Unmarried,Black,Female,0,4356,40,United-States,<=50K

In [301]:
adult_in_d['relationship'] = label_en.fit_transform(adult_in_d['relationship'])
adult_in_d['relationship'].value_counts()

relationship
0    13193
1     8305
3     5068
4     3446
5     1568
2      981
Name: count, dtype: int64

In [302]:
adult_in_d['race'] = label_en.fit_transform(adult_in_d['race'])
adult_in_d['race'].value_counts()

race
4    27816
2     3124
1     1039
0      311
3      271
Name: count, dtype: int64

In [303]:
adult_in_d['sex'] = label_en.fit_transform(adult_in_d['sex'])
adult_in_d['sex'].value_counts()

sex
1    21790
0    10771
Name: count, dtype: int64

In [304]:
adult_in_d['income'] = label_en.fit_transform(adult_in_d['income'])
adult_in_d['income'].value_counts()

income
0    24720
1     7841
Name: count, dtype: int64

In [305]:
adult_in_d.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,0,77053,11,9,6,0,1,4,0,0,4356,40,United-States,0
1,82,4,132870,11,9,6,4,1,4,0,0,4356,18,United-States,0
2,66,0,186061,15,10,6,0,4,2,0,0,4356,40,United-States,0
3,54,4,140359,5,4,0,7,4,4,0,0,3900,40,United-States,0
4,41,4,264663,15,10,5,10,3,4,0,0,3900,40,United-States,0

In [306]:
adult_in_d['native.country']= label_en.fit_transform(adult_in_d['native.country'])
adult_in_d['native.country'].value_counts()

native.country
39    29170
26      643
0       583
30      198
11      137
2       121
33      114
8       106
19      100
5        95
9        90
23       81
35       80
3        75
22       73
6        70
40       67
13       64
24       62
31       60
4        59
36       51
14       44
20       43
32       37
27       34
29       31
12       29
10       29
7        28
21       24
17       20
38       19
1        19
37       18
25       18
41       16
28       14
18       13
16       13
34       12
15        1
Name: count, dtype: int64

In [307]:
adult_in_d.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,0,77053,11,9,6,0,1,4,0,0,4356,40,39,0
1,82,4,132870,11,9,6,4,1,4,0,0,4356,18,39,0
2,66,0,186061,15,10,6,0,4,2,0,0,4356,40,39,0
3,54,4,140359,5,4,0,7,4,4,0,0,3900,40,39,0
4,41,4,264663,15,10,5,10,3,4,0,0,3900,40,39,0

In [308]:
penguin_data_set = sns.load_dataset("penguins")

In [309]:
penguin_data_set

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [310]:
penguin_data_set.shape

(344, 7)

In [311]:
penguin_data_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object
dtypes: float64(4), object(3)
memory usage: 18.9+ KB

In [312]:
penguin_data_set.isna().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [313]:
penguin_data_set['bill_length_mm'] = penguin_data_set['bill_length_mm'].fillna(penguin_data_set['bill_length_mm'].mean())

In [314]:
penguin_data_set['bill_depth_mm'] = penguin_data_set['bill_depth_mm'].fillna(penguin_data_set['bill_depth_mm'].mean())

In [315]:
penguin_data_set['flipper_length_mm'] = penguin_data_set['flipper_length_mm'].fillna(penguin_data_set['flipper_length_mm'].mean())

In [316]:
penguin_data_set['body_mass_g'] = penguin_data_set['body_mass_g'].fillna(penguin_data_set['body_mass_g'].mean())

In [317]:
penguin_data_set['sex'] = penguin_data_set['sex'].ffill()

In [318]:
penguin_data_set.isna().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

In [319]:
penguin_data_set.columns

Index(['species', 'island', 'bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex'],
      dtype='object')

In [320]:
for col in penguin_data_set.loc[:,['species', 'island','sex']]:
    val = penguin_data_set[col].value_counts()
    print(val)

species
Adelie       152
Gentoo       124
Chinstrap     68
Name: count, dtype: int64
island
Biscoe       168
Dream        124
Torgersen     52
Name: count, dtype: int64
sex
Male      177
Female    167
Name: count, dtype: int64

In [321]:
for col in penguin_data_set.loc[:,['species','island','sex']]:
    uni = penguin_data_set[col].nunique()
    print(uni)

3
3
2

In [322]:
for col in penguin_data_set.columns:
    if is_numeric_dtype(penguin_data_set[col]):
        continue
    else:
        uni = penguin_data_set[col].nunique()
        val = penguin_data_set[col].unique().tolist()
        if uni == 2:
            penguin_data_set[col] = penguin_data_set[col].replace(val,[0,1])
        elif uni == 3:
            penguin_data_set[col] = penguin_data_set[col].replace(val,[0,1,2])

C:\Users\MD Maruf\AppData\Local\Temp\ipykernel_8612\3495431927.py:10: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  penguin_data_set[col] = penguin_data_set[col].replace(val,[0,1,2])
C:\Users\MD Maruf\AppData\Local\Temp\ipykernel_8612\3495431927.py:8: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  penguin_data_set[col] = penguin_data_set[col].replace(val,[0,1])

In [323]:
penguin_data_set.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,0,0,39.10000,18.70000,181.000000,3750.000000,0
1,0,0,39.50000,17.40000,186.000000,3800.000000,1
2,0,0,40.30000,18.00000,195.000000,3250.000000,1
3,0,0,43.92193,17.15117,200.915205,4201.754386,1
4,0,0,36.70000,19.30000,193.000000,3450.000000,1

In [324]:
titan_data_set = sns.load_dataset('titanic')

In [325]:
titan_data_set_copy = titan_data_set.copy()

In [326]:
titan_data_set.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [327]:
titan_data_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [328]:
titan_data_set.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [329]:
titan_data_set.drop('deck', axis=1, inplace=True)

In [330]:
titan_data_set['age'] = titan_data_set['age'].fillna(titan_data_set['age'].mean())

In [331]:
titan_data_set['embark_town'] = titan_data_set['embark_town'].ffill()

In [332]:
titan_data_set['embarked'] = titan_data_set['embarked'].ffill()

In [333]:
titan_data_set.isna().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

In [334]:
titan_data_set.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'embark_town', 'alive',
       'alone'],
      dtype='object')

In [335]:
titan_data_set.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

In [336]:
for col in titan_data_set.loc[:, ['adult_male', 'alone']]:
    titan_data_set[col] = titan_data_set[col].astype('int64')
    titan_data_set

In [337]:
titan_data_set.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,1,Southampton,no,0
1,1,1,female,38.0,1,0,71.2833,C,First,woman,0,Cherbourg,yes,0
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,0,Southampton,yes,1
3,1,1,female,35.0,1,0,53.1000,S,First,woman,0,Southampton,yes,0
4,0,3,male,35.0,0,0,8.0500,S,Third,man,1,Southampton,no,1

In [338]:
titan_data_set['class'].value_counts()

class
Third     491
First     216
Second    184
Name: count, dtype: int64

In [339]:
for col in titan_data_set.columns:
    if is_numeric_dtype(titan_data_set[col]):
        continue
    else:
        uni = titan_data_set[col].nunique()
        val = titan_data_set[col].unique().tolist()
        if uni == 2:
            titan_data_set[col] = titan_data_set[col].replace(val, [0,1])
        elif uni == 3:
            titan_data_set[col] = titan_data_set[col].replace(val, [0,1,2])
        elif uni == 4:
            titan_data_set[col] = titan_data_set[col].replace(val, [0,1,2,3])

C:\Users\MD Maruf\AppData\Local\Temp\ipykernel_8612\534995522.py:8: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  titan_data_set[col] = titan_data_set[col].replace(val, [0,1])
C:\Users\MD Maruf\AppData\Local\Temp\ipykernel_8612\534995522.py:10: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  titan_data_set[col] = titan_data_set[col].replace(val, [0,1,2])
C:\Users\MD Maruf\AppData\Local\Temp\ipykernel_8612\534995522.py:10: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  titan_data_set[col] = titan_data_set[col].replace(val, [0,1,2])
C:\Users\MD Maruf\AppData\Local\Temp\ipykernel_8612\534995522.py:10: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  titan_data_set[col] = titan_data_set[col].replace(val, [0,1,2])
C:\Users\MD Maruf\AppData\Local\Temp\ipykernel_8612\534995522.py:8: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  titan_data_set[col] = titan_data_set[col].replace(val, [0,1])

In [340]:
titan_data_set.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,0,22.0,1,0,7.2500,0,0,0,1,0,0,0
1,1,1,1,38.0,1,0,71.2833,1,1,1,0,1,1,0
2,1,3,1,26.0,0,0,7.9250,0,0,1,0,0,1,1
3,1,1,1,35.0,1,0,53.1000,0,1,1,0,0,1,0
4,0,3,0,35.0,0,0,8.0500,0,0,0,1,0,0,1

In [341]:
titan_data_set_copy.drop('deck', axis=1, inplace=True)

In [342]:
titan_data_set_copy['age'] = titan_data_set_copy['age'].fillna(titan_data_set_copy['age'].mean())

In [343]:
titan_data_set_copy['embark_town'] = titan_data_set_copy['embark_town'].ffill()

In [344]:
titan_data_set_copy['embarked'] = titan_data_set_copy['embarked'].ffill()

In [346]:
titan_data_set_copy.isna().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

In [347]:
for col in titan_data_set_copy.columns:
    if is_numeric_dtype(titan_data_set_copy[col]):
        continue
    else:
        titan_data_set_copy[col] = label_en.fit_transform(titan_data_set_copy[col])

In [348]:
titan_data_set_copy.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,1,22.0,1,0,7.2500,2,2,1,True,2,0,False
1,1,1,0,38.0,1,0,71.2833,0,0,2,False,0,1,False
2,1,3,0,26.0,0,0,7.9250,2,2,2,False,2,1,True
3,1,1,0,35.0,1,0,53.1000,2,0,2,False,2,1,False
4,0,3,1,35.0,0,0,8.0500,2,2,1,True,2,0,True

In [350]:
for col in titan_data_set_copy.iloc[:, [10, 13]]:
    titan_data_set_copy[col] = titan_data_set_copy[col].astype('int64')

In [351]:
titan_data_set_copy.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,1,22.0,1,0,7.2500,2,2,1,1,2,0,0
1,1,1,0,38.0,1,0,71.2833,0,0,2,0,0,1,0
2,1,3,0,26.0,0,0,7.9250,2,2,2,0,2,1,1
3,1,1,0,35.0,1,0,53.1000,2,0,2,0,2,1,0
4,0,3,1,35.0,0,0,8.0500,2,2,1,1,2,0,1

Label encoding end