In [50]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler, MaxAbsScaler
import seaborn as sns
from sklearn.datasets import load_diabetes

In [4]:
titanic_data = sns.load_dataset("titanic")

In [5]:
titanic_data.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [6]:
titanic_data.shape

(891, 15)

In [7]:
titanic_data.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [8]:
titanic_data.drop('deck', axis=1, inplace=True)

In [9]:
titanic_data.head(2)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False

In [10]:
titanic_data['age'] = titanic_data['age'].fillna(titanic_data['age'].mean())

In [11]:
titanic_data['embarked'] = titanic_data['embarked'].bfill()

In [12]:
titanic_data['embark_town'] = titanic_data['embark_town'].bfill()

In [13]:
titanic_data.isna().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

In [14]:
titanic_data.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

Normalization

In [15]:
minmax = MinMaxScaler()

In [16]:
titanic_data['age'] = minmax.fit_transform(titanic_data[['age']])

In [17]:
titanic_data.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,0.271174,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,0.472229,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,0.321438,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,0.434531,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,0.434531,0,0,8.0500,S,Third,man,True,Southampton,no,True

In [18]:
titanic_data['fare'] = minmax.fit_transform(titanic_data[['fare']])

In [19]:
titanic_data.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,0.271174,1,0,0.014151,S,Third,man,True,Southampton,no,False
1,1,1,female,0.472229,1,0,0.139136,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,0.321438,0,0,0.015469,S,Third,woman,False,Southampton,yes,True
3,1,1,female,0.434531,1,0,0.103644,S,First,woman,False,Southampton,yes,False
4,0,3,male,0.434531,0,0,0.015713,S,Third,man,True,Southampton,no,True

In [20]:
wine_dataset = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv', sep=';')
wine_dataset.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [51]:
wine_dataset1 = wine_dataset.copy()
wine_dataset2 = wine_dataset.copy()
wine_dataset3 = wine_dataset.copy()
wine_dataset4 = wine_dataset.copy()
wine_dataset5 = wine_dataset.copy()
wine_dataset6 = wine_dataset.copy()
wine_dataset7 = wine_dataset.copy()
wine_dataset8 = wine_dataset.copy()
wine_dataset9 = wine_dataset.copy()

In [22]:
wine_dataset['fixed acidity'] = minmax.fit_transform(wine_dataset[['fixed acidity']])
wine_dataset.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,0.247788,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,0.283186,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,0.283186,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,0.584071,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,0.247788,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [23]:
wine_dataset.iloc[:, [1,2,3,4,5,6,7,8,9,10]].head(2)

,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
0,0.70,0.0,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4
1,0.88,0.0,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8

In [24]:
for col in wine_dataset.iloc[:, [1,2,3,4,5,6,7,8,9,10]]:
    wine_dataset[col] = minmax.fit_transform(wine_dataset[[col]])
wine_dataset.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,0.247788,0.397260,0.00,0.068493,0.106845,0.140845,0.098940,0.567548,0.606299,0.137725,0.153846,5
1,0.283186,0.520548,0.00,0.116438,0.143573,0.338028,0.215548,0.494126,0.362205,0.209581,0.215385,5
2,0.283186,0.438356,0.04,0.095890,0.133556,0.197183,0.169611,0.508811,0.409449,0.191617,0.215385,5
3,0.584071,0.109589,0.56,0.068493,0.105175,0.225352,0.190813,0.582232,0.330709,0.149701,0.215385,6
4,0.247788,0.397260,0.00,0.068493,0.106845,0.140845,0.098940,0.567548,0.606299,0.137725,0.153846,5

Standardization

In [25]:
wine_dataset1.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [26]:
standard = StandardScaler()

In [27]:
wine_dataset1['fixed acidity'] = standard.fit_transform(wine_dataset1[['fixed acidity']])

In [28]:
wine_dataset1.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,-0.528360,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,-0.298547,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,-0.298547,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,1.654856,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,-0.528360,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [29]:
wine_dataset1['volatile acidity'] = standard.fit_transform(wine_dataset1[['volatile acidity']])
wine_dataset1.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,-0.528360,0.961877,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,-0.298547,1.967442,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,-0.298547,1.297065,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,1.654856,-1.384443,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,-0.528360,0.961877,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [30]:
for col in wine_dataset1.iloc[:, 2:11]:
    wine_dataset1[col] = standard.fit_transform(wine_dataset1[[col]])
wine_dataset1.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,-0.528360,0.961877,-1.391472,-0.453218,-0.243707,-0.466193,-0.379133,0.558274,1.288643,-0.579207,-0.960246,5
1,-0.298547,1.967442,-1.391472,0.043416,0.223875,0.872638,0.624363,0.028261,-0.719933,0.128950,-0.584777,5
2,-0.298547,1.297065,-1.186070,-0.169427,0.096353,-0.083669,0.229047,0.134264,-0.331177,-0.048089,-0.584777,5
3,1.654856,-1.384443,1.484154,-0.453218,-0.264960,0.107592,0.411500,0.664277,-0.979104,-0.461180,-0.584777,6
4,-0.528360,0.961877,-1.391472,-0.453218,-0.243707,-0.466193,-0.379133,0.558274,1.288643,-0.579207,-0.960246,5

Log Transformation

In [31]:
wine_dataset2.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [32]:
wine_dataset2['fixed acidity'] = np.log10(wine_dataset2[['fixed acidity']])

In [33]:
wine_dataset2.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,0.869232,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,0.892095,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,0.892095,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,1.049218,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,0.869232,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [34]:
for col in wine_dataset2.iloc[:, 1:11]:
    wine_dataset2[col] = np.log10(wine_dataset2[[col]])
wine_dataset2.head()

c:\Users\MD Maruf\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\internals\blocks.py:395: RuntimeWarning: divide by zero encountered in log10
  result = func(self.values, **kwargs)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,0.869232,-0.154902,-inf,0.278754,-1.119186,1.041393,1.531479,-0.000957,0.545307,-0.251812,0.973128,5
1,0.892095,-0.055517,-inf,0.414973,-1.008774,1.397940,1.826075,-0.001392,0.505150,-0.167491,0.991226,5
2,0.892095,-0.119186,-1.397940,0.361728,-1.036212,1.176091,1.732394,-0.001305,0.513218,-0.187087,0.991226,5
3,1.049218,-0.552842,-0.251812,0.278754,-1.124939,1.230449,1.778151,-0.000869,0.499687,-0.236572,0.991226,6
4,0.869232,-0.154902,-inf,0.278754,-1.119186,1.041393,1.531479,-0.000957,0.545307,-0.251812,0.973128,5

In [35]:
wine_dataset3 = np.log10(wine_dataset3)

c:\Users\MD Maruf\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\internals\blocks.py:395: RuntimeWarning: divide by zero encountered in log10
  result = func(self.values, **kwargs)

In [36]:
wine_dataset3.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,0.869232,-0.154902,-inf,0.278754,-1.119186,1.041393,1.531479,-0.000957,0.545307,-0.251812,0.973128,0.698970
1,0.892095,-0.055517,-inf,0.414973,-1.008774,1.397940,1.826075,-0.001392,0.505150,-0.167491,0.991226,0.698970
2,0.892095,-0.119186,-1.397940,0.361728,-1.036212,1.176091,1.732394,-0.001305,0.513218,-0.187087,0.991226,0.698970
3,1.049218,-0.552842,-0.251812,0.278754,-1.124939,1.230449,1.778151,-0.000869,0.499687,-0.236572,0.991226,0.778151
4,0.869232,-0.154902,-inf,0.278754,-1.119186,1.041393,1.531479,-0.000957,0.545307,-0.251812,0.973128,0.698970

Robust Scaler

In [38]:
robust = RobustScaler()

In [40]:
wine_dataset4.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [41]:
wine_dataset4['fixed acidity'] = robust.fit_transform(wine_dataset4[['fixed acidity']])

In [43]:
wine_dataset4.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,-0.238095,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,-0.047619,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,-0.047619,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,1.571429,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,-0.238095,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [45]:
for col in wine_dataset4.iloc[:, 1:11]:
    wine_dataset4[col] = robust.fit_transform(wine_dataset4[[col]])
wine_dataset4.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,-0.238095,0.72,-0.787879,-0.428571,-0.15,-0.214286,-0.100,0.469799,1.052632,-0.333333,-0.50,5
1,-0.047619,1.44,-0.787879,0.571429,0.95,0.785714,0.725,0.022371,-0.578947,0.333333,-0.25,5
2,-0.047619,0.96,-0.666667,0.142857,0.65,0.071429,0.400,0.111857,-0.263158,0.166667,-0.25,5
3,1.571429,-0.96,0.909091,-0.428571,-0.20,0.214286,0.550,0.559284,-0.789474,-0.222222,-0.25,6
4,-0.238095,0.72,-0.787879,-0.428571,-0.15,-0.214286,-0.100,0.469799,1.052632,-0.333333,-0.50,5

In [46]:
insu_data = pd.read_csv("M:\Machine Learning Start with CIT\data files\insurance (1).csv")

In [47]:
insu_data.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [48]:
insu_data['charges'] = robust.fit_transform(insu_data[['charges']])

In [49]:
insu_data.head()

   age     sex     bmi  children smoker     region   charges
0   19  female  27.900         0    yes  southwest  0.630515
1   18    male  33.770         1     no  southeast -0.643422
2   28    male  33.000         3     no  southeast -0.414515
3   33    male  22.705         0     no  northwest  1.059062
4   32    male  28.880         0     no  northwest -0.463475

Max Absolute Scaler