In [3]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
import seaborn as sns

In [13]:
titanic_data = sns.load_dataset("titanic")

In [14]:
titanic_data.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [15]:
titanic_data.shape

(891, 15)

In [16]:
titanic_data.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [18]:
titanic_data.drop('deck', axis=1, inplace=True)

In [20]:
titanic_data.head(2)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False

In [27]:
titanic_data['age'] = titanic_data['age'].fillna(titanic_data['age'].mean())

In [28]:
titanic_data['embarked'] = titanic_data['embarked'].bfill()

In [29]:
titanic_data['embark_town'] = titanic_data['embark_town'].bfill()

In [30]:
titanic_data.isna().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

In [31]:
titanic_data.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

In [32]:
minmax = MinMaxScaler()

In [34]:
titanic_data['age'] = minmax.fit_transform(titanic_data[['age']])

In [35]:
titanic_data.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,0.271174,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,0.472229,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,0.321438,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,0.434531,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,0.434531,0,0,8.0500,S,Third,man,True,Southampton,no,True

In [38]:
titanic_data['fare'] = minmax.fit_transform(titanic_data[['fare']])

In [39]:
titanic_data.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,0.271174,1,0,0.014151,S,Third,man,True,Southampton,no,False
1,1,1,female,0.472229,1,0,0.139136,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,0.321438,0,0,0.015469,S,Third,woman,False,Southampton,yes,True
3,1,1,female,0.434531,1,0,0.103644,S,First,woman,False,Southampton,yes,False
4,0,3,male,0.434531,0,0,0.015713,S,Third,man,True,Southampton,no,True